apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - image: obsidiandynamics/kafka
          name: kafka
          resources:
            requests:
              memory: "1024Mi"
              cpu: "25m"
            limits:
              memory: "2048Mi"
              cpu: "200m"
          env:
            - name: KAFKA_LISTENERS
              value: "INTERNAL://:29092,EXTERNAL://:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka:29092,EXTERNAL://kafka:9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_ZOOKEEPER_SESSION_TIMEOUT
              value: "6000"
            - name: KAFKA_RESTART_ATTEMPTS
              value: "10"
            - name: KAFKA_RESTART_DELAY
              value: "5"
            - name: ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL
              value: "0"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
          ports:
            - containerPort: 2181
            - containerPort: 9092
            - containerPort: 29092
