apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka
spec:
  ports:
    - name: 'tcp-external'
      port: 9092
      protocol: TCP
      targetPort: 9092
    - name: 'tcp-internal'
      port: 29092
      protocol: TCP
      targetPort: 29092
  selector:
    app: kafka
  type: ClusterIP
