apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: moderation
  name: moderation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation
  template:
    metadata:
      labels:
        app: moderation
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/pet-pproject/moderation/production
          name: moderation
          resources:
            requests:
              memory: "64Mi"
              cpu: "25m"
            limits:
              memory: "256Mi"
              cpu: "50m"
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3004"
            - name: KAFKA_BROKERCONNECT
              value: kafka:29092
          ports:
            - containerPort: 3004
