apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafdrop
  name: kafdrop
spec:
  ports:
    - name: 'tcp'
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: kafdrop
  type: ClusterIP
