apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reviews
  name: reviews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/pet-pproject/reviews/production
          name: reviews
          resources:
            requests:
              memory: "64Mi"
              cpu: "25m"
            limits:
              memory: "256Mi"
              cpu: "100m"
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3001"
            - name: KAFKA_BROKERCONNECT
              value: kafka:29092
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_DB
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_SYNCHRONIZE
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_SYNCHRONIZE
          ports:
            - containerPort: 3001
