apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: books
  name: books
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books
  template:
    metadata:
      labels:
        app: books
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/pet-pproject/books/production
          name: books
          resources:
            requests:
              memory: "64Mi"
              cpu: "25m"
            limits:
              memory: "256Mi"
              cpu: "100m"
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3002"
            - name: KAFKA_BROKERCONNECT
              value: kafka:29092
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_DB
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_SYNCHRONIZE
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_SYNCHRONIZE
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: REDIS_PORT
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elasticsearch
                  key: ELASTICSEARCH_USERNAME
            - name: ELASTICSEARCH_NODE
              valueFrom:
                  secretKeyRef:
                    name: elasticsearch
                    key: ELASTICSEARCH_NODE
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch
                  key: ELASTICSEARCH_PASSWORD
          ports:
            - containerPort: 3002
