apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/pet-pproject/api-gateway/production
          name: api-gateway
          resources:
            requests:
              memory: "64Mi"
              cpu: "25m"
            limits:
              memory: "256Mi"
              cpu: "100m"
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
            - name: KAFKA_BROKERCONNECT
              value: kafka:29092
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_DB
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_SYNCHRONIZE
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_SYNCHRONIZE
            - name: WEBHOOK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: webhook-secrets
                  key: WEBHOOK_API_KEY
          ports:
            - containerPort: 3000
